### ISSUE TITLE
helm install faild 

### ISSUE THREAD

**Issue by Jolin-blank** [devtron-labs/devtron#1472]
kubectl logs 
2022/04/06 02:08:03 ERROR #42P01 relation "gitops_config" does not exist
panic: ERROR #42P01 relation "gitops_config" does not exist

goroutine 1 [running]:
log.Panic(0xc000b39f68, 0x1, 0x1)
        /usr/local/go/src/log/log.go:354 +0xae
main.main()
        /go/src/github.com/devtron-labs/devtron/main.go:32 +0x7d

pgsql:
![Uploading 1649212521008.jpg…]()

Due to network reasons, manually execute the files in script / SQL, but it still doesn't work

**Comment by Jolin-blank** [comment]
relation "gitops_config" does not exist at character 484
