### ISSUE TITLE
SES Configuration not working for notifications

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#2030]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

SES Configuration not working for notifications

**To Reproduce**

1. Add configurations for SES
2. Add notification for same SES
3. Try to trigger the event/pipeline and see if you get a notification

**Expected behavior**

Email should have been received

**Current behavior** 

No email received

**Logs**
 
```
{"level":"warn","message":"email-ses-provider 400 - <ErrorResponse xmlns=\"http://ses.amazonaws.com/doc/2010-12-01/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>InvalidParameterValue</Code>\n    <Message>Missing required header 'From'.</Message>\n  </Error>\n  <RequestId>ae4e7662-9d6a-4f5f-a290-2db03e9e7d5b</RequestId>\n</ErrorResponse>\n","stack":"Error: 400 - <ErrorResponse xmlns=\"http://ses.amazonaws.com/doc/2010-12-01/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>InvalidParameterValue</Code>\n    <Message>Missing required header 'From'.</Message>\n  </Error>\n  <RequestId>ae4e7662-9d6a-4f5f-a290-2db03e9e7d5b</RequestId>\n</ErrorResponse>\n\n    at EmailSesProvider._callee$ (/app/node_modules/notifme-sdk/lib/providers/email/ses.js:144:23)\n    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)\n    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)\n    at Generator.prototype.<computed> [as next] (/app/node_modules/regenerator-runtime/runtime.js:114:21)\n    at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)\n    at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
```

**Comment by deepak-devtron** [comment]
This has been fixed and deployed so closing it.
