### ISSUE TITLE
Bug: impossible configure GitOps, Bad Gateway

### ISSUE THREAD

**Issue by Giancarlo1974** [devtron-labs/devtron#2511]
### 📜 Description

When i try to configure Gitops i got the error Bad Gateway
i am logged as admin

### 👟 Reproduction steps

1. Install devtron-operator (0.22.39) via helm chart 
2. log in as admin user
3. Go in "Global Configurations" --> "GitOps"
4. Compile form (GitHub Organisation Name*, GitHub Username*, Personal Access Token*) => Token has full control
5. Click "Save" you will see "Validating repo configuration. Please wait…" and then "Bad Gateway"
6. See Error logs in devtron pod:
`/service-worker.js
/service-worker.js
{"level":"info","ts":1666168314.5921035,"caller":"restHandler/GitOpsConfigRestHandler.go:94","msg":"request payload, CreateGitOpsConfig","err":null,"payload":{"provider":"GITHUB","username":"MyUsername","token":"MyToken","gitLabGroupId":"","gitHubOrgId":"myorganization","host":"https://github.com/","active":true,"azureProjectName":"","bitBucketWorkspaceId":"","bitBucketProjectKey":""}}
{"level":"info","ts":1666168314.5922139,"caller":"util/GitService.go:152","msg":"client changed successfully"}
{"level":"error","ts":1666168314.5939546,"caller":"util/ChartService.go:599","msg":"error in getting emailId from active gitOps config","err":"pg: no rows in result set","stacktrace":"github.com/devtron-labs/devtron/internal/util.(*ChartTemplateServiceImpl).GetUserEmailIdAndNameForGitOpsCommit\n\t/go/src/github.com/devtron-labs/devtron/internal/util/ChartService.go:599\ngithub.com/devtron-labs/devtron/pkg/gitops.(*GitOpsConfigServiceImpl).GitOpsValidateDryRun\n\t/go/src/github.com/devtron-labs/devtron/pkg/gitops/GitOpsConfigService.go:705\ngithub.com/devtron-labs/devtron/pkg/gitops.(*GitOpsConfigServiceImpl).ValidateAndCreateGitOpsConfig\n\t/go/src/github.com/devtron-labs/devtron/pkg/gitops/GitOpsConfigService.go:128\ngithub.com/devtron-labs/devtron/api/restHandler.GitOpsConfigRestHandlerImpl.CreateGitOpsConfig\n\t/go/src/github.com/devtron-labs/devtron/api/restHandler/GitOpsConfigRestHandler.go:101\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:72\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210\ngithub.com/devtron-labs/authenticator/middleware.Authorizer.func1.1\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:62\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1966"}
{"level":"info","ts":1666168316.4928176,"caller":"util/GitService.go:722","msg":"github repo created ","r":"https://github.com/myorganization/devtron-sample-repo-dryrun-l3oqeh.git"}
{"level":"error","ts":1666168317.2681816,"caller":"zap/sugar.go:179","msg":"Ignored key without a value.","ignored":"MyUsername","stacktrace":"go.uber.org/zap.(*SugaredLogger).Infow\n\t/go/src/github.com/devtron-labs/devtron/vendor/go.uber.org/zap/sugar.go:179\ngithub.com/devtron-labs/devtron/internal/util.(*GitCliUtil).Clone\n\t/go/src/github.com/devtron-labs/devtron/internal/util/GitCliUtil.go:105\ngithub.com/devtron-labs/devtron/internal/util.GitServiceImpl.Clone\n\t/go/src/github.com/devtron-labs/devtron/internal/util/GitService.go:543\ngithub.com/devtron-labs/devtron/internal/util.GitHubClient.ensureProjectAvailabilityOnSsh\n\t/go/src/github.com/devtron-labs/devtron/internal/util/GitService.go:855\ngithub.com/devtron-labs/devtron/internal/util.GitHubClient.CreateRepository\n\t/go/src/github.com/devtron-labs/devtron/internal/util/GitService.go:745\ngithub.com/devtron-labs/devtron/pkg/gitops.(*GitOpsConfigServiceImpl).GitOpsValidateDryRun\n\t/go/src/github.com/devtron-labs/devtron/pkg/gitops/GitOpsConfigService.go:706\ngithub.com/devtron-labs/devtron/pkg/gitops.(*GitOpsConfigServiceImpl).ValidateAndCreateGitOpsConfig\n\t/go/src/github.com/devtron-labs/devtron/pkg/gitops/GitOpsConfigService.go:128\ngithub.com/devtron-labs/devtron/api/restHandler.GitOpsConfigRestHandlerImpl.CreateGitOpsConfig\n\t/go/src/github.com/devtron-labs/devtron/api/restHandler/GitOpsConfigRestHandler.go:101\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:72\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210\ngithub.com/devtron-labs/authenticator/middleware.Authorizer.func1.1\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware
/AuthMiddleware.go:62\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1966"}
{"level":"info","ts":1666168317.2681618,"caller":"util/GitCliUtil.go:105","msg":"input","/tmp/gitops/ensure-clone/devtron-sample-repo-dryrun-l3oqeh":"https://github.com/myorganization/devtron-sample-repo-dryrun-l3oqeh.git"}
{"level":"warn","ts":1666168318.213346,"caller":"util/GitCliUtil.go:112","msg":"git fetch completed, pulling master branch data from remote origin"}
{"level":"info","ts":1666168318.2158337,"caller":"util/GitCliUtil.go:115","msg":"[origin/master]"}
{"level":"info","ts":1666168318.9235783,"caller":"util/GitService.go:857","msg":"github ensureProjectAvailability clone passed","try count":1,"repoUrl":"https://github.com/myorganization/devtron-sample-repo-dryrun-l3oqeh.git"}
{"level":"error","ts":1666168318.9236841,"caller":"zap/sugar.go:179","msg":"Ignored key without a value.","ignored":"MyUsername","stacktrace":"go.uber.org/zap.(*SugaredLogger).Infow\n\t/go/src/github.com/devtron-labs/devtron/vendor/go.uber.org/zap/sugar.go:179\ngithub.com/devtron-labs/devtron/internal/util.(*GitCliUtil).Clone\n\t/go/src/github.com/devtron-labs/devtron/internal/util/GitCliUtil.go:105\ngithub.com/devtron-labs/devtron/internal/util.GitServiceImpl.Clone\n\t/go/src/github.com/devtron-labs/devtron/internal/util/GitService.go:543\ngithub.com/devtron-labs/devtron/pkg/gitops.(*GitOpsConfigServiceImpl).GitOpsValidateDryRun\n\t/go/src/github.com/devtron-labs/devtron/pkg/gitops/GitOpsConfigService.go:730\ngithub.com/devtron-labs/devtron/pkg/gitops.(*GitOpsConfigServiceImpl).ValidateAndCreateGitOpsConfig\n\t/go/src/github.com/devtron-labs/devtron/pkg/gitops/GitOpsConfigService.go:128\ngithub.com/devtron-labs/devtron/api/restHandler.GitOpsConfigRestHandlerImpl.CreateGitOpsConfig\n\t/go/src/github.com/devtron-labs/devtron/api/restHandler/GitOpsConfigRestHandler.go:101\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:72\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210\ngithub.com/devtron-labs/authenticator/middleware.Authorizer.func1.1\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:62\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1966"}
{"level":"info","ts":1666168318.923677,"caller":"util/GitCliUtil.go:105","msg":"input","/tmp/gitops/devtron-sample-repo-dryrun-l3oqeh-7256513715813642463":"https://github.com/myorganization/devtron-sample-repo-dryrun-l3oqeh.git"}
{"level":"warn","ts":1666168319.799407,"caller":"util/GitCliUtil.go:112","msg":"git fetch completed, pulling master branch data from remote origin"}
{"level":"info","ts":1666168319.8040988,"caller":"util/GitCliUtil.go:115","msg":"[origin/master]"}
{"level":"info","ts":1666168320.005851,"caller":"pipeline/CdHandler.go:133","msg":"received deployment statuses for stucked argo cd pipelines","deploymentStatuses":null}
{"level":"info","ts":1666168320.0071962,"caller":"pipeline/CdHandler.go:249","msg":"checking helm app status for deployment triggers","pipelineOverrides":null}
2022/10/19 08:32:01 http: panic serving 192.168.35.14:45560: runtime error: invalid memory address or nil pointer dereference
goroutine 1180 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x461a0a0, 0x6f0b0a0})
/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/devtron-labs/devtron/client/argocdServer.GetTLS(0x0)
/go/src/github.com/devtron-labs/devtron/client/argocdServer/Tls.go:38 +0xae
github.com/devtron-labs/devtron/client/argocdServer.GetConnection({0x0, 0x0}, 0xc000c431e0)
/go/src/github.com/devtron-labs/devtron/client/argocdServer/Connection.go:40 +0xaf
github.com/devtron-labs/devtron/client/argocdServer/session.NewSessionServiceClient(0x0?)
/go/src/github.com/devtron-labs/devtron/client/argocdServer/session/Session.go:37 +0x25
github.com/devtron-labs/devtron/util/argo.passwordLogin(0x0?, {0xc000c72cc6, 0x7}, {0xc000c72ce0, 0x10})
/go/src/github.com/devtron-labs/devtron/util/argo/ArgoUserService.go:323 +0x2d
github.com/devtron-labs/devtron/util/argo.(*ArgoUserServiceImpl).createTokenForArgoCdUser(0xc000e53d80, {0xc000c72cc6, 0x7}, {0xc000c72ce0?, 0xc0015bace8?})
/go/src/github.com/devtron-labs/devtron/util/argo/ArgoUserService.go:303 +0x52
github.com/devtron-labs/devtron/util/argo.(*ArgoUserServiceImpl).createNewArgoCdTokenForDevtron(0xc000e53d80, {0xc000c72cc6?, 0x10?}, {0xc000c72ce0?, 0x0?}, 0x0?, 0xbe8?)
/go/src/github.com/devtron-labs/devtron/util/argo/ArgoUserService.go:147 +0x50
github.com/devtron-labs/devtron/util/argo.(*ArgoUserServiceImpl).GetOrUpdateArgoCdUserDetail(0xc000e53d80)
/go/src/github.com/devtron-labs/devtron/util/argo/ArgoUserService.go:114 +0x509
github.com/devtron-labs/devtron/pkg/gitops.(*GitOpsConfigServiceImpl).ValidateAndCreateGitOpsConfig(0xc0003ccc80, 0xc0013c0e70)
/go/src/github.com/devtron-labs/devtron/pkg/gitops/GitOpsConfigService.go:131 +0x115
github.com/devtron-labs/devtron/api/restHandler.GitOpsConfigRestHandlerImpl.CreateGitOpsConfig({0xc0000109d8, {0x52dd4b8, 0xc0003ccc80}, {0x52e7440, 0xc00017d500}, 0xc00017d5c0, {0x52dc760, 0xc000e53280}, {0x52dc6b0, 0xc000d16090}, ...}, ...)
/go/src/github.com/devtron-labs/devtron/api/restHandler/GitOpsConfigRestHandler.go:101 +0x6aa
net/http.HandlerFunc.ServeHTTP(0x52cf7d0?, {0x7f4c844e42c0?, 0xc0015e5450?}, 0x90?)
/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1({0x52cf7d0, 0xc000c3eee0}, 0xc000c41a00)
/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:72 +0x232
net/http.HandlerFunc.ServeHTTP(0xc000c41900?, {0x52cf7d0?, 0xc000c3eee0?}, 0xc0015bb868?)
/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0009aa600, {0x52cf7d0, 0xc000c3eee0}, 0xc000c41800)
/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210 +0x1cf
github.com/devtron-labs/authenticator/middleware.Authorizer.func1.1({0x52cf7d0, 0xc000c3eee0}, 0xc000c41800)
/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:62 +0x3a9
net/http.HandlerFunc.ServeHTTP(0x0?, {0x52cf7d0?, 0xc000c3eee0?}, 0x17d0e65?)
/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0x52b6168?}, {0x52cf7d0, 0xc000c3eee0}, 0xc000c41800)
/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0003cd540, {0x52d1f48, 0xc0013bb350})
/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:3071 +0x4db`

### 👍 Expected behavior

it should save the settings

### 👎 Actual Behavior

When Click "Save" you will see
**Validating repo configuration. Please wait…**
and then
**Bad Gateway**

### 💻 Device

Desktop/Laptop

### 💻 Operating system

Linux

### 🌍 Browser

Chrome

### 🧱 Your Environment

I use
Chrome Version 106.0.5249.119 (Build ufficial) (64 bit)
Kubernetes v1.20.11 (via Rancher RKE)

### ✅ Proposed Solution

In the logs i see

**http: panic serving 192.168.35.14:45560: runtime error: invalid memory address or nil pointer dereference**

You shoud fix the procedure function

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#934

**Comment by felipemachado12** [comment]
Same problem here.

**Comment by prakarsh-dt** [comment]
Can you share the output of
`kubectl get jobs -n devtroncd`
and 
`kubectl get pod -n devtrponcd`

**Comment by Giancarlo1974** [comment]
I have currently uninstalled devtron
@felipemachado12 Can you share the output of
`kubectl get jobs -n devtroncd`
and
`kubectl get pod -n devtrponcd`

**Comment by felipemachado12** [comment]
```
# kubectl get jobs -n devtroncd
NAME                               COMPLETIONS   DURATION   AGE
app-manual-sync-job                1/1           17s        15h
app-sync-cronjob-1667847600        1/1           11s        2d18h
app-sync-cronjob-1667934000        1/1           17s        42h
app-sync-cronjob-1668020400        1/1           26s        18h
devtron-housekeeping               1/1           3m48s      12d
grafana-org-job                    1/1           75s        42h
postgresql-migrate-casbin          1/1           26s        42h
postgresql-migrate-casbin-gigjh    1/1           21s        39h
postgresql-migrate-devtron         1/1           21s        42h
postgresql-migrate-devtron-xuypj   1/1           33s        39h
postgresql-migrate-gitsensor       1/1           5s         42h
postgresql-migrate-lens            1/1           4s         42h
```

```
# kubectl get pod -n devtroncd
NAME                                     READY   STATUS      RESTARTS   AGE
app-manual-sync-job-8kpkz                0/1     Completed   0          15h
app-sync-cronjob-1667847600-hhj7f        0/1     Completed   0          2d18h
app-sync-cronjob-1667934000-rmdl2        0/1     Completed   0          42h
app-sync-cronjob-1668020400-m7zrj        0/1     Completed   0          18h
argo-rollouts-5765664fc4-5zfcq           1/1     Running     0          2d15h
argocd-application-controller-0          1/1     Running     0          40h
argocd-dex-server-77dcd488b6-rhtv9       1/1     Running     0          2d15h
argocd-redis-59c979d8bd-chvsj            1/1     Running     0          40h
argocd-repo-server-5cb9c69b6-pw245       1/1     Running     0          40h
argocd-server-fcf476bf5-2xxc2            1/1     Running     3          40h
clair-856db5987b-ghj47                   1/1     Running     0          39h
dashboard-84c9c485-h4gcn                 1/1     Running     0          42h
devtron-79c4df7d85-g4jh5                 1/1     Running     0          39h
devtron-grafana-7597fd5c67-p9h69         2/2     Running     0          42h
devtron-grafana-test                     0/1     Completed   3          42h
devtron-nats-0                           3/3     Running     0          2d19h
devtron-nats-test-request-reply          0/1     Completed   0          42h
git-sensor-0                             1/1     Running     4          2d15h
grafana-org-job-jx257                    0/1     Completed   0          42h
image-scanner-7f57b5b6f7-9thjc           1/1     Running     0          39h
inception-bf7c77cc5-qdf46                1/1     Running     0          2d15h
kubelink-598448fd98-6rxd2                1/1     Running     0          2d15h
kubewatch-67d8949bc9-jfgnz               1/1     Running     0          2d15h
lens-5f6fd69b59-qkj6r                    1/1     Running     4          2d15h
notifier-d658c9bc8-vpr62                 1/1     Running     0          2d15h
postgresql-migrate-casbin-b7gnh          0/1     Completed   0          42h
postgresql-migrate-casbin-gigjh-kqpts    0/1     Completed   0          39h
postgresql-migrate-devtron-bbt9n         0/1     Completed   0          42h
postgresql-migrate-devtron-xuypj-588bm   0/1     Completed   0          39h
postgresql-migrate-gitsensor-fnqz6       0/1     Completed   0          42h
postgresql-migrate-lens-cwc24            0/1     Completed   0          42h
postgresql-postgresql-0                  2/2     Running     1          2d15h
```

**Comment by prakarsh-dt** [comment]
> ```
> # kubectl get jobs -n devtroncd
> NAME                               COMPLETIONS   DURATION   AGE
> app-manual-sync-job                1/1           17s        15h
> app-sync-cronjob-1667847600        1/1           11s        2d18h
> app-sync-cronjob-1667934000        1/1           17s        42h
> app-sync-cronjob-1668020400        1/1           26s        18h
> devtron-housekeeping               1/1           3m48s      12d
> grafana-org-job                    1/1           75s        42h
> postgresql-migrate-casbin          1/1           26s        42h
> postgresql-migrate-casbin-gigjh    1/1           21s        39h
> postgresql-migrate-devtron         1/1           21s        42h
> postgresql-migrate-devtron-xuypj   1/1           33s        39h
> postgresql-migrate-gitsensor       1/1           5s         42h
> postgresql-migrate-lens            1/1           4s         42h
> ```
> 
> ```
> # kubectl get pod -n devtroncd
> NAME                                     READY   STATUS      RESTARTS   AGE
> app-manual-sync-job-8kpkz                0/1     Completed   0          15h
> app-sync-cronjob-1667847600-hhj7f        0/1     Completed   0          2d18h
> app-sync-cronjob-1667934000-rmdl2        0/1     Completed   0          42h
> app-sync-cronjob-1668020400-m7zrj        0/1     Completed   0          18h
> argo-rollouts-5765664fc4-5zfcq           1/1     Running     0          2d15h
> argocd-application-controller-0          1/1     Running     0          40h
> argocd-dex-server-77dcd488b6-rhtv9       1/1     Running     0          2d15h
> argocd-redis-59c979d8bd-chvsj            1/1     Running     0          40h
> argocd-repo-server-5cb9c69b6-pw245       1/1     Running     0          40h
> argocd-server-fcf476bf5-2xxc2            1/1     Running     3          40h
> clair-856db5987b-ghj47                   1/1     Running     0          39h
> dashboard-84c9c485-h4gcn                 1/1     Running     0          42h
> devtron-79c4df7d85-g4jh5                 1/1     Running     0          39h
> devtron-grafana-7597fd5c67-p9h69         2/2     Running     0          42h
> devtron-grafana-test                     0/1     Completed   3          42h
> devtron-nats-0                           3/3     Running     0          2d19h
> devtron-nats-test-request-reply          0/1     Completed   0          42h
> git-sensor-0                             1/1     Running     4          2d15h
> grafana-org-job-jx257                    0/1     Completed   0          42h
> image-scanner-7f57b5b6f7-9thjc           1/1     Running     0          39h
> inception-bf7c77cc5-qdf46                1/1     Running     0          2d15h
> kubelink-598448fd98-6rxd2                1/1     Running     0          2d15h
> kubewatch-67d8949bc9-jfgnz               1/1     Running     0          2d15h
> lens-5f6fd69b59-qkj6r                    1/1     Running     4          2d15h
> notifier-d658c9bc8-vpr62                 1/1     Running     0          2d15h
> postgresql-migrate-casbin-b7gnh          0/1     Completed   0          42h
> postgresql-migrate-casbin-gigjh-kqpts    0/1     Completed   0          39h
> postgresql-migrate-devtron-bbt9n         0/1     Completed   0          42h
> postgresql-migrate-devtron-xuypj-588bm   0/1     Completed   0          39h
> postgresql-migrate-gitsensor-fnqz6       0/1     Completed   0          42h
> postgresql-migrate-lens-cwc24            0/1     Completed   0          42h
> postgresql-postgresql-0                  2/2     Running     1          2d15h
> ```

Still same issue?

**Comment by nishant-d** [comment]
we have identified the issue, we will be fixed in next release. 

workaroud:
restart the devtron pod once after argocd installation is success.

**Comment by satyampsoni** [comment]
Not relevant as of 2025
