### ISSUE TITLE
Bug: Can't rename cluster

### ISSUE THREAD

**Issue by nbragin4** [devtron-labs/devtron#4200]
### 📜 Description

when i trying to click on edit button, devtron throws error.

### 👟 Reproduction steps

1. go to https://{{devtron.url}}/dashboard/global-config/cluster-env
2. try to rename cluster
3. get error

### 👍 Expected behavior

Rename cluster should work

### 👎 Actual Behavior

![image](https://github.com/devtron-labs/devtron/assets/139489942/2773acf1-42ea-4093-a190-b0fd839a911c)

### ☸ Kubernetes version

K8S 1.25

### Cloud provider

<details>
Yandex Cloud
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

Looks like Admin (default Admin) user cannot be found in users.

here are logs:
<details>
<pre>
react-dom.production.min.js:5309  TypeError: Cannot read properties of undefined (reading 'user')
    at we (Cluster.tsx:835:64)
    at na (react-dom.production.min.js:3848:7)
    at Ba (react-dom.production.min.js:4494:7)
    at qs (react-dom.production.min.js:7017:86)
    at wc (react-dom.production.min.js:6411:11)
    at Ac (react-dom.production.min.js:6400:5)
    at Mc (react-dom.production.min.js:6382:7)
    at fc (react-dom.production.min.js:6103:28)
    at react-dom.production.min.js:2898:17
    at scheduler.production.min.js:289:12
is @ react-dom.production.min.js:5309
n.payload @ react-dom.production.min.js:5344
ui @ react-dom.production.min.js:3137
Wa @ react-dom.production.min.js:4539
qs @ react-dom.production.min.js:7020
wc @ react-dom.production.min.js:6411
Ac @ react-dom.production.min.js:6400
Mc @ react-dom.production.min.js:6382
fc @ react-dom.production.min.js:6103
(anonymous) @ react-dom.production.min.js:2898
(anonymous) @ scheduler.production.min.js:289
Fo @ react-dom.production.min.js:2868
Xo @ react-dom.production.min.js:2893
Uo @ react-dom.production.min.js:2883
sc @ react-dom.production.min.js:5933
Ta @ react-dom.production.min.js:4231
(anonymous) @ Cluster.tsx:467
u @ runtime.js:64
(anonymous) @ runtime.js:278
(anonymous) @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
Ve @ Cluster.tsx:321
onClick @ Cluster.tsx:321
Fe @ react-dom.production.min.js:913
Ge @ react-dom.production.min.js:933
(anonymous) @ react-dom.production.min.js:937
wr @ react-dom.production.min.js:2162
Sr @ react-dom.production.min.js:2190
(anonymous) @ react-dom.production.min.js:2552
Pe @ react-dom.production.min.js:7596
(anonymous) @ react-dom.production.min.js:857
Nr @ react-dom.production.min.js:2288
Zt @ react-dom.production.min.js:1565
Jt @ react-dom.production.min.js:1526
(anonymous) @ scheduler.production.min.js:289
Fo @ react-dom.production.min.js:2868
ze @ react-dom.production.min.js:7581
Qt @ react-dom.production.min.js:1512
cluster-env:1  The resource https://fonts.googleapis.com/css?family=Open+Sans was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
</pre>
</details>

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by pawan-mehta-dt** [comment]
@nbragin4 What's the devtron version that you are using?

**Comment by nbragin4** [comment]
@pawan-mehta-dt devtron v0.6.24

**Comment by pawan-mehta-dt** [comment]
Can you try in incognito mode if it allows you to edit cluster?

**Comment by nbragin4** [comment]
no, just the same behavior. also changing account from Admin to OIDC user's account not helps
