### ISSUE TITLE
Bug: i/o timeout while launching devtron deployment, login dashboard never launches

### ISSUE THREAD

**Issue by arnoldas500** [devtron-labs/devtron#4356]
### 📜 Description

When trying to deploy using helm the lens, kubelink and devtron deployments never launch sucessfully. 

Output logs are the same in all the failing deployments:
{"level":"error","ts":1701815358.4070756,"caller":"sql/connection.go:63","msg":"error in connecting db ","db":{"Addr":"postgresql-postgresql.devtroncd","Port":"5432","User":"postgres","Password":"********","Database":"orchestrator","ApplicationName":"orchestrator","LogQuery":true,"LogAllQuery":false,"ExportPromMetrics":false,"QueryDurationThreshold":5000},"err":"dial tcp 10.233.53.22:5432: i/o timeout","stacktrace":"github.com/devtron-labs/devtron/pkg/sql.NewDbConnection\n\t/go/src/github.com/devtron-labs/devtron/pkg/sql/connection.go:63\nmain.InitializeApp\n\t/go/src/github.com/devtron-labs/devtron/wire_gen.go:169\nmain.main\n\t/go/src/github.com/devtron-labs/devtron/main.go:32\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
2023/12/05 22:29:18 dial tcp 10.233.53.22:5432: i/o timeout
panic: dial tcp 10.233.53.22:5432: i/o timeout

goroutine 1 [running]:
log.Panic({0xc000f3ff60?, 0x19abf3c?, 0xc000f3ff70?})
	/usr/local/go/src/log/log.go:384 +0x65
main.main()
	/go/src/github.com/devtron-labs/devtron/main.go:34 +0x4f

### 👟 Reproduction steps

when I run :
helm install devtron devtron/devtron-operator --create-namespace --namespace devtroncd --set installer.modules={cicd} --set minio.enabled=true --set argo-cd.enabled=true --set components.devtron.service.type=NodePort

or helm install devtron devtron/devtron-operator --create-namespace --namespace devtroncd --set installer.modules={cicd} --set minio.enabled=true --set argo-cd.enabled=true 

### 👍 Expected behavior

Deployment to launch and dashboard to load

### 👎 Actual Behavior

if I launch with nodeport, curl 10.233.17.15:32417/dashboard or curl 10.233.17.15:32417 gives connection refused. Deployments never launch. 

If launched with loadbalancer the ip address also gives connection refused and dashboard cannot be accessed. Same deployments also stuck in crashback loop.

### ☸ Kubernetes version

Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.5

### Cloud provider

<details>
Bare Metal Cluster
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by badal773** [comment]
Hello [arnoldas500](https://github.com/arnoldas500) , Could you please verify the current status of the PostgreSQL database in the "devtroncd" namespace? There seems to be an issue with the connection, and I need you to check if the PostgreSQL pod is still running.

1. Confirm the stateful set status:   `kubectl get sts -n devtroncd`
2. Describe the PostgreSQL pod for more details: `kubectl describe pod/postgresql-postgresql-0 -n devtroncd`
3. List the pods in the "devtroncd" namespace to check the status of pods:  `kubectl get po -n devtroncd`

**Comment by arnoldas500** [comment]
Hi @badal773, Here are the outputs for the 3 steps above:
1. kubectl get sts -n devtroncd
postgresql-postgresql   1/1     17h
2. kubectl describe pod/postgresql-postgresql-0 -n devtroncd
Name:             postgresql-postgresql-0
Namespace:        devtroncd
Priority:         0
Service Account:  default
Node:             **********************
Start Time:       Tue, 05 Dec 2023 18:05:13 -0500
Labels:           app=postgresql
                  chart=postgresql-8.6.4
                  controller-revision-hash=postgresql-postgresql-5d4cc658bd
                  release=devtron
                  role=master
                  statefulset.kubernetes.io/pod-name=postgresql-postgresql-0
Annotations:      cni.projectcalico.org/containerID: 1c4ce689b52ffd55a24ad84bf04ab8031c144d4f0847f154a69718c1fff77051
                  cni.projectcalico.org/podIP: 10.233.70.4/32
                  cni.projectcalico.org/podIPs: 10.233.70.4/32
Status:           Running
IP:               10.233.70.4
IPs:
  IP:           10.233.70.4
Controlled By:  StatefulSet/postgresql-postgresql
Init Containers:
  init-chmod-data:
    Container ID:  docker://34be5eaa915d40f449d93778e4ef73e93edc97348c7a77867aaa4c4d259bc32e
    Image:         quay.io/devtron/minideb:latest
    Image ID:      docker-pullable://quay.io/devtron/minideb@sha256:78ee17c9bfc2e35af5ce817fd683c108a694c4a8d033bf0a14bc7bf115c357b7
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -cx

      mkdir -p /bitnami/postgresql/data
      chmod 700 /bitnami/postgresql/data
      find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
        xargs chown -R 1001:1001
      chmod -R 777 /dev/shm

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 05 Dec 2023 18:05:19 -0500
      Finished:     Tue, 05 Dec 2023 18:05:19 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /bitnami/postgresql from data (rw)
      /dev/shm from dshm (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5qhpn (ro)
Containers:
  postgresql-postgresql:
    Container ID:   docker://d8d5e07aa9469df346f9a768359f5dfb29ebf43f5257e4cc9fc39825269a853d
    Image:          quay.io/devtron/postgres:11.9.0-debian-10-r26
    Image ID:       docker-pullable://quay.io/devtron/postgres@sha256:9d851f80d206279fb1ada9abba7465629103dd4ea0584d60d1203ef2aa0791a2
    Port:           5432/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 05 Dec 2023 18:05:19 -0500
    Ready:          True
    Restart Count:  0
    Liveness:       exec [/bin/sh -c exec pg_isready -U "postgres" -d "orchestrator" -h 127.0.0.1 -p 5432] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:      exec [/bin/sh -c -e exec pg_isready -U "postgres" -d "orchestrator" -h 127.0.0.1 -p 5432
[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                        false
      POSTGRESQL_PORT_NUMBER:               5432
      POSTGRESQL_VOLUME_DIR:                /bitnami/postgresql
      PGDATA:                               /bitnami/postgresql/data
      POSTGRES_USER:                        postgres
      POSTGRES_PASSWORD:                    <set to the key 'postgresql-password' in secret 'postgresql-postgresql'>  Optional: false
      POSTGRES_DB:                          orchestrator
      POSTGRESQL_ENABLE_LDAP:               no
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES:  pgaudit, uuid-ossp
    Mounts:
      /bitnami/postgresql from data (rw)
      /dev/shm from dshm (rw)
      /docker-entrypoint-initdb.d/ from custom-init-scripts (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5qhpn (ro)
  metrics:
    Container ID:   docker://47447f5fd8660616de88513500e968e4c53ec4b12f45913278fa91f7d8a1f6e4
    Image:          quay.io/devtron/postgres_exporter:v0.4.7
    Image ID:       docker-pullable://quay.io/devtron/postgres_exporter@sha256:dd8051322ceb8995d3d7f116041a2116815e01e88232a90f635ebde8dcc4d3f4
    Port:           9187/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 05 Dec 2023 18:05:22 -0500
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:http-metrics/ delay=5s timeout=5s period=10s #success=1 #failure=6
    Readiness:      http-get http://:http-metrics/ delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      DATA_SOURCE_URI:   127.0.0.1:5432/orchestrator?sslmode=disable
      DATA_SOURCE_PASS:  <set to the key 'postgresql-password' in secret 'postgresql-postgresql'>  Optional: false
      DATA_SOURCE_USER:  postgres
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5qhpn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-postgresql-postgresql-0
    ReadOnly:   false
  custom-init-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      postgresql-postgresql-init-scripts
    Optional:  false
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  1Gi
  kube-api-access-5qhpn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>

3. kubectl get po -n devtroncd
app-sync-job-jq4mr-hc95j            0/1     Init:0/1           0                 17h
argocd-dex-server-9fb99cf5f-dnq4h   1/1     Running            0                 17h
dashboard-77dd4c6665-njcm7          1/1     Running            0                 17h
devtron-6856959fb9-wvq2f            0/1     CrashLoopBackOff   210 (4m23s ago)   17h
kubelink-784c7d77cc-kk2jj           0/1     CrashLoopBackOff   211 (97s ago)     17h
postgresql-postgresql-0             2/2     Running            0                 17h

**Comment by pawan-mehta-dt** [comment]
@arnoldas500 are you using any proxy in your cluster?

**Comment by arnoldas500** [comment]
> @arnoldas500 are you using any proxy in your cluster?

No I am not

**Comment by pawan-mehta-dt** [comment]
@arnoldas500 any kind of firewall on network of cluster? Also, can you share if coredns pods are running in cluster without any issues?

Are you running in other applications on K8s in same cluster?

**Comment by arnoldas500** [comment]
it ended up being a firewall issue. Seems to be working without issues now.
